# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeoApp
pod 'RealmSwift'

  target 'LeoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeoAppUITests' do
    # Pods for testing
  end

end
